apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: financial-portal
  namespace: financial-portal
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - portal.xyz-financial.com
      secretName: portal-tls
  rules:
    - host: portal.xyz-financial.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: financial-portal
                port:
                  number: 80
